DROP TABLE IF EXISTS to_do_item;
CREATE TABLE IF NOT EXISTS to_do_item (id INTEGER PRIMARY KEY AUTO_INCREMENT, description VARCHAR(200) NOT NULL, priority INTEGER NOT NULL, `time` TIMESTAMP NOT NULL, completed BOOLEAN NOT NULL);
